# --- 개발 스테이지 ---
# Nuxt.js 개발 환경을 위한 스테이지입니다.
FROM node:20-alpine

# 컨테이너 내부의 작업 디렉토리를 /app으로 설정합니다.
# 이 디렉토리는 docker-compose.yml에서 호스트의 소스 코드와 볼륨 마운트될 것입니다.
WORKDIR /app

# pnpm 패키지 매니저를 설치합니다.
RUN npm install -g pnpm

# 의존성 설치를 위해 package.json과 pnpm-lock.yaml 파일을 먼저 복사합니다.
# 이렇게 하면 소스 코드가 변경되어도 의존성이 변경되지 않으면 Docker 캐시를 활용할 수 있습니다.
# Dockerfile이 프로젝트 루트에 있고 Nuxt 앱이 'nuxt' 하위 디렉토리에 있다고 가정합니다.
COPY ./nuxt/package.json ./
COPY ./nuxt/pnpm-lock.yaml ./

# pnpm을 사용하여 프로젝트 의존성을 설치합니다.
RUN pnpm install

# Nuxt.js 개발 서버가 수신 대기할 포트를 노출합니다.
EXPOSE 3000

# 컨테이너가 시작될 때 실행될 기본 명령어입니다.
# Nuxt.js 개발 서버를 시작합니다.
# 이 명령어는 docker-compose.yml의 'command'에 의해 재정의될 수 있습니다.
CMD ["pnpm", "dev"]
